### ISSUE TITLE
Does the task-dependent connectivity between some regions in the frontoparietal system and the hippocampus correlate the emotional n-back task performance?

### ISSUE THREAD

**Issue by mmpeng9** [ABCD-ReproNim/projects#20]
## Research question(s)

Does the task-dependent connectivity between some regions in the frontoparietal system and the hippocampus correlate the emotional n-back task performance?

## Description

The frontoparietal activation when doing working memory tasks is a reliable marker of the working memory ability(Rosenberg et al., 2020). However, the hippocampus also contributes to working memory. Patients with hippocampus lesions exhibited deficits in working memory (Koen et al., 2017). 
The proposed project will compute the correlation between the connectivity of the frontoparietal areas and the hippocampus with the emotional n-back task performance. The sub-regions will be defined by structural templates or PCA.

## Tools and algorithms to be used

Functional connectivity
Brain-behavior relationship
Replication
Python

**Comment by jessicabartley** [comment]
Unfortunately, we're closing this proposal due to a DUC status issue. We invite anyone who has already joined this project team to consider joining another project for the duration of Project Week. Thanks!
