### ISSUE TITLE
The Potential Resilient Effects of Playing a Musical Instrument on Neuro Developmental Outcomes in Children From Low Socioeconomic Backgrounds

### ISSUE THREAD

**Issue by rbenno48** [ABCD-ReproNim/projects#22]
## Title
The Potential Resilient Effects of Playing a Musical Instrument on  Neuro Developmental Outcomes in Children from Low Socioeconomic Status Backgrounds

## Research question(s)
Can early music education overcome some of the risks for compromised brain development and behavior in children of low socioeconomic status (SES) ? Do these beneficial effects of playing music correlate with the length of time, intensity, and quality of playing the instrument?

## Description
Previous work (Hennessy et al., 2019) suggests that music education during development engages areas of the brain responsible for executive functioning leading to better decision making, better memory, focused memory, and impulse control. In addition, music education has been shown to strengthen networks that process sounds, language, and communication. A recent study (Gonzalez et al., 2020) utilizing data from the ABCD study have shown that there are associations of low SES with lower cortical surface area and poorer cognitive performance in 9-10-year old children in this cohort. The data suggests that positive economic, psychosocial, and physiological ecologies might ameliorate risks of these developmental outcomes.
In this study, we will examine if early music education can act similarly to the positive proximal measures as defined in the study by Gonzalez et., (2020) upon developmental outcomes. In addition to analyzing total cortical surface area and cognitive performance, we will attempt to extend this analysis to look at other factors such as impulse control and attention with a focus on fMRI activity during the Stop Signal Task in the region of  the parstriangularis (rh) of the right anterior frontal cortex, an area known to be involved in impulse control (Garavan et al., 1999) . In addition, we will attempt to correlate these findings with behavioral measures of impulsivity such as self-reporting via the UPPS-P test, outside reporting of impulsivity from parents or teachers, and behavioral measures of performance utilizing the Flanker test for impulsivity and impulsivity. 	

## Tools and algorithms to be used
DEAP and whatever skills team members can bring to this project.
## Skills we could use help with (optional)

I am not a computer scientist and have limited ability to work on this project other than through the DEAP procedure. Whatever programming and statistical skills you can bring to this project would be extremely helpful.
## Suggested keywords/tags
Socioeconomic Status (SES) 
Playing a musical instrument
Cognitive Performance
Total Cortical Surface Area
Stop Signal Task
Functional MRI of the cort.Desikan_parstriangularis.rh
Impulsivity
Flanker Task

## References:

Garavan, H., Ross,T.J. , and Stein, E.A.. Right hemispheric dominance of inhibitory control: an event-related functional MRI study. Proceedings of the National Academy of Sciences, 1999: 96 (14), 8301-8306.

Gonzalez, M.R., Palmer, C.E., Uban, K.A., Jernigan, T.L., Thompson, W.K., and Sowell, E.R. Positive Economic, Psychosocial and Physiological Ecologies Predict Brain Structure and Cognitive Performance in 9-10-Year-Old Children. Frontiers in Human Neuroscience, October 2020: 14: Article 578822

Hennessey, S. L,  Sachs, M.E,  Llari, B., and Habibi, A. Effects of Musical Training on Inhibitory Control and Associated Neural Networks in School-Aged Children: A Longitudinal Study. Frontiers in Neuroscience . 2019: 13: 1080.

**Comment by jessicabartley** [comment]
We've closed this project at the request of @rbenno48.

**Comment by rbenno48** [comment]
Jessica. I think that my presentation is out of context now. It’s not necessary for me to say anything at this point. Thanks again fir everything. It was an interesting week and I learned a lot 👍🏼

**Comment by jessicabartley** [comment]
No worries Bob! I’m so sorry that you experienced technical difficulties and were not able to share the progress you made with the rest of us this past week. We were plagued a bit by technical difficulties at today’s presentations (it wasn’t just you). I’m glad you feel you learned a lot, though. I hope you had an enjoyable time working with your group!
