### ISSUE TITLE
The Effects of Playing a Musical Instrument Upon Brain Development and Impulsive Behavior in the ABCD Study

### ISSUE THREAD

**Issue by rbenno48** [ABCD-ReproNim/projects#8]
**Research Question**

Playing a musical instrument during the period of adolescence is associated with better attention and inhibitory control. The overall beneficial effects upon brain development and behavior should corelate with the length of  time and intensity of playing of the instrument.

**Description**

Previous work (Hennessy et al., 2019) suggests that music education during development engages areas of the brain responsible for executive functioning leading to better decision making, better memory, focused memory and impulse control. In addition, music education has been shown to strengthen networks that process sounds, language and communication. Although this study by Hennessy et al. (2019) differs from the ABCD study in several methodological issues,  comparison of data in the two studies could strengthen or refute the earlier findings, and in addition shed some light on the issue as to whether impulsivity is a broad construct, which can be studied from varied approaches. 
In this study, I will investigate the effects of playing a musical instrument upon impulsivity and attention in subjects participating in the ABCD study. The initial study will be done on baseline data. When DEAP incorporates longitudinal analyses, I will extend this analysis to determine if there are changes in brain development and behavior in individuals over time.  I will look specifically at  the effects of early music education on impulsivity and attention as measured in the following ways:

Music Education: 
          (1) Report of playing a musical instrument 
For example, using the variable: scrn_hr_music

Behavioral Measures:  
  (1) Self reporting of impulsivity through analysis of the UPPS-P test
For example, using the variable: upps_ss_lack_of_perseverance

  (2) Outside reporting of Impulsivity from parents or teachers
For example, using the variable: bpmt _q9 (teacher monitoring) 

 (3) Behavior performance analysis utilizing the Flanker test for attention and impulsivity
For example, using the variable: nihtbx_flanker_uncorrected

Imaging measures:        
 (1) fMRI analysis focusing on the Right Anterior Frontal Cortex when the  subjects  are performing the Stop Signal Task (Garavan et al., 1999)
For example, using the variable:   tfmri_sst_all_any.stop.vs.correct.go_beta_cort.Desikan_parstriangularis.rh

 (1a) Analysis of  variable: cort.Desikan__parstriangularis (rh) and (lh) with handedness subsets

**Keywords**

Stop Signal Task
Functional MRI of the cort.Desikan_parstriangularis.rh
Impulsivity
Flanker Task
Playing a musical instrument

**References**

Garavan, H., Ross,T.J. , and Stein, E.A.. Right hemispheric dominance of inhibitory control: an event-related functional MRI study. Proceedings of the National Academy of Sciences, 96 (14), 8301-8306.

Hennessey, S. L,  Sachs, ME, Llari, B., and Habibi, A. Effects of Musical Training on Inhibitory Control and Associated Neural Networks in School-Aged Children: A Longitudinal Study. Frontiers in Neuroscience . 2019: 13: 1080.

**Contact:**

Robert Benno
William Paterson University of New Jersey - Emeritus Professor of Biology
rbenno48@gmail.com

**Comment by jessicabartley** [comment]
After communication with @rbenno48, this proposal has been updated and resubmitted as a new proposal! Check out "The Potential Resilient Effects of Playing a Musical Instrument on Neuro Developmental Outcomes in Children From Low Socioeconomic Backgrounds" (#22) if anyone is interested in contributing to this idea!
